name: Build docker image
run-name: ${{ github.actor }} / Build docker image ðŸ³

on:
  push:
    branches:
    - main
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DB_HOST: localhost
      BUILD_DB_NAME: themepark
      BUILD_DB_USERNAME: 'username'
      BUILD_DB_PASSWORD: 'password'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: build gradle
        run: |
          export MYSQL_DATABASE=$BUILD_DB_NAME
          export MYSQL_USER=$BUILD_DB_USERNAME
          export MYSQL_PASSWORD=$BUILD_DB_PASSWORD
          docker run -d --name db -e MYSQL_RANDOM_ROOT_PASSWORD=yes  -e MYSQL_DATABASE -e MYSQL_USER -e MYSQL_PASSWORD -p 3306:3306 mysql:8.0

          export DB_URL=`echo jdbc:mysql://$BUILD_DB_HOST:3306/$BUILD_DB_NAME`
          export DB_USERNAME=$BUILD_DB_USERNAME
          export DB_PASSWORD=$BUILD_DB_PASSWORD
          sed -i "s/CI_PIPELINE_IID/${{ github.run_id }}/" ./src/main/resources/application.yml
          sed -i "s/CI_COMMIT_SHORT_SHA/${{ github.sha }}/" ./src/main/resources/application.yml
          sed -i "s/CI_COMMIT_BRANCH/${{ github.ref_name }}/" ./src/main/resources/application.yml
          ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Release Version
        run: |
          echo "IMAGE_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build -t p0l1na/themeparkride:1.0.${{ env.IMAGE_TAG }} -f Dockerfile .
          docker build -t p0l1na/themeparkride:latest -f Dockerfile .

      - name: Push Image
        run: |
          docker push p0l1na/themeparkride:1.0.${{ env.IMAGE_TAG }}
          docker push p0l1na/themeparkride:latest
